server:
  port: 3000
#  host: 172.31.39.23
  servlet:
    session:
      cookie.name: bfb4c74f0

spring:
  # 레디스 설정
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  # 데이터 베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:XE
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: ${ddl.auto}

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB #30메가까지는 임시로 넣고 넘으면 다른곳에 저장하는거

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

# 파일 업로드 경로
file:
  upload.path: ${file.path}
  upload.url: ${file.url}

# Swagger API 설정
springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /apidocs.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**